//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WebFresher042023.Demo.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceVN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceVN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WebFresher042023.Demo.Core.Resources.ResourceVN", typeof(ResourceVN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoàng Minh Đức.
        /// </summary>
        public static string Author_Excel {
            get {
                return ResourceManager.GetString("Author_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản không được phép để trống..
        /// </summary>
        public static string Empty_Code {
            get {
                return ResourceManager.GetString("Empty_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên tài sản không được phép để trống..
        /// </summary>
        public static string Empty_Name {
            get {
                return ResourceManager.GetString("Empty_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản bị trùng. Vui lòng nhập lại..
        /// </summary>
        public static string Error_Dupli_Code {
            get {
                return ResourceManager.GetString("Error_Dupli_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra vui lòng liên hệ MISA để được trợ giúp..
        /// </summary>
        public static string Error_Exception {
            get {
                return ResourceManager.GetString("Error_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tài sản không được vượt quá 20 kí tự..
        /// </summary>
        public static string Error_Length_Code {
            get {
                return ResourceManager.GetString("Error_Length_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tài sản không tồn tại. Vui lòng thử lại..
        /// </summary>
        public static string Error_NotExit_Asset {
            get {
                return ResourceManager.GetString("Error_NotExit_Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày sử dụng vượt quá ngày hiện tại. Vui lòng nhập lại..
        /// </summary>
        public static string Error_ProductionYear {
            get {
                return ResourceManager.GetString("Error_ProductionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua vượt quá ngày hiện tại. Vui lòng nhập lại..
        /// </summary>
        public static string Error_PurchaseDate {
            get {
                return ResourceManager.GetString("Error_PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ngày mua phải nhỏ hơn ngày sử dụng. Vui lòng nhập lại..
        /// </summary>
        public static string Error_PurchaseDateAndProductionYear {
            get {
                return ResourceManager.GetString("Error_PurchaseDateAndProductionYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu không hợp lệ. Vui lòng nhập lại..
        /// </summary>
        public static string Error_Validate {
            get {
                return ResourceManager.GetString("Error_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lỗi nhập dữ liệu do người dùng..
        /// </summary>
        public static string Error_Validate_Dev {
            get {
                return ResourceManager.GetString("Error_Validate_Dev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Danh sách tài sản.
        /// </summary>
        public static string Title_Excel {
            get {
                return ResourceManager.GetString("Title_Excel", resourceCulture);
            }
        }
    }
}
